name: sh1mccci

on:
  push:
  pull_request:

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run_build
        working-directory: ./
        run: |
          make

  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run_test
        working-directory: ./
        run: |
          make test